### ISSUE TITLE
initial task list (tdhc before 29/05)

### ISSUE THREAD

**Issue by tdhc153** [tdhc153/starmast#1]
- [x] write readme
- [x] finish style guide
- [x] finish intro to quadratics
- [x] finish questions for intro to quadratics
- [x] finish solutions to intro to quadratics
- [x] write content list as issues
- [x] write announcement
- [x] commit :)
